### ISSUE TITLE
Why do you set local_coords=False in sampling

### ISSUE THREAD

**Issue by Luciennnnnnn** [facebookresearch/riemannian-fm#4]
Hi, I noticed that by default, during sampling, you set `local_coords=False` and. Why do you use `xt + dt * vt` instead of `manifold.expmap(xt, dt * vt)`? The later is more appropriated to manifold.

**Comment by rtqichen** [comment]
I don't think it made much of a difference in the experiments. On manifolds where expmap is known, the main setting where samples can leave the manifold is the hypersphere. I often checked whether the samples have left the manifold (e.g. https://github.com/facebookresearch/riemannian-fm/blob/main/manifm/model_pl.py#L525-L530) and it turns out that using the simple integrator was fine.

**Comment by Luciennnnnnn** [comment]
Hi @rtqichen ,thank you for your explanation. I noticed that you always set `eval_projx=True`, which means the results are projected back onto the manifold at each step, so the final result is obviously on the manifold. However, my confusion lies in understanding the difference between `xt + dt * vt` and `manifold.expmap(xt, dt * vt)`. Could you please explain this specifically?
